name: Super Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "11"

      - name: Run Super Linter
        uses: github/super-linter@v5.7.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-lint: "false"
          css-lint: "false"
          docker-lint: "false"
          go-lint: "false"
          html-lint: "false"
          java-lint: "true"
          javascript-lint: "false"
          json-lint: "false"
          markdown-lint: "false"
          php-lint: "false"
          python-lint: "false"
          ruby-lint: "false"
          shell-lint: "false"
          yaml-lint: "false"
